<?php
/**
 * @filesource /include/custom_settings.php
 * UI settings (overridable). Do not edit this file manually
 * Use /admin/ui_settings.php to modify these settings via web-interface
 */

// Interface elements
define('SHOW_AUDIO_MONITOR', true);
define('SHOW_MACROS', true);
define('SHOW_CON_DETAILS', true);
define('SHOW_RADIO_ACTIVITY', true);
define('SHOW_NET_ACTIVITY', true);
define('SHOW_RF_ACTIVITY', true);

// History tables limits
define('NET_ACTIVITY_LIMIT', 10);
define('RF_ACTIVITY_LIMIT', 5);

// WebSocket real-time updates
define('WS_ENABLED', true);

// AJAX update interval (ms)
define('UPDATE_INTERVAL', 3000);

// Multilanguage support
define('LANGUAGE_SUPPORT', true);

// Debug mode
define('DEBUG', false);
define('DEBUG_VERBOSE', 4);
define('DEBUG_WEB_CONSOLE', true);
define('DEBUG_LOG_CONSOLE', false);