<?php

/**
 * UI Settings Editor
 * @filesource /include/ui_settings.php
 * @author Vladimir Tsurkanenko <vladimir@tsurkanenko.ru>
 * @date 2026.02.21
 * @version 0.4.0
 */

require_once $_SERVER["DOCUMENT_ROOT"] . "/include/init.php";

if (!isset($_SESSION['auth']) || $_SESSION['auth'] !== 'AUTHORISED') {
	header('HTTP/1.0 403 Forbidden');
	exit;
}

require_once $_SERVER["DOCUMENT_ROOT"] . "/include/fn/getTranslation.php";
$message = '';
$messageType = '';
$customSettingsFile = $_SERVER["DOCUMENT_ROOT"] . "/include/custom_settings.php";

// Load current settings
$settings = [
	'SHOW_AUDIO_MONITOR' => defined('SHOW_AUDIO_MONITOR') ? SHOW_AUDIO_MONITOR : true,
	'SHOW_MACROS' => defined('SHOW_MACROS') ? SHOW_MACROS : true,
	'SHOW_CON_DETAILS' => defined('SHOW_CON_DETAILS') ? SHOW_CON_DETAILS : true,
	'SHOW_RADIO_ACTIVITY' => defined('SHOW_RADIO_ACTIVITY') ? SHOW_RADIO_ACTIVITY : true,
	'SHOW_NET_ACTIVITY' => defined('SHOW_NET_ACTIVITY') ? SHOW_NET_ACTIVITY : true,
	'NET_ACTIVITY_LIMIT' => defined('NET_ACTIVITY_LIMIT') ? NET_ACTIVITY_LIMIT : 10,
	'SHOW_RF_ACTIVITY' => defined('SHOW_RF_ACTIVITY') ? SHOW_RF_ACTIVITY : true,
	'RF_ACTIVITY_LIMIT' => defined('RF_ACTIVITY_LIMIT') ? RF_ACTIVITY_LIMIT : 5,
	'WS_ENABLED' => defined('WS_ENABLED') ? WS_ENABLED : true,
	'UPDATE_INTERVAL' => defined('UPDATE_INTERVAL') ? UPDATE_INTERVAL : 3000,
	'LANGUAGE_SUPPORT' => defined('LANGUAGE_SUPPORT') ? LANGUAGE_SUPPORT : false,
	'DEBUG' => defined('DEBUG') ? DEBUG : false,
	'DEBUG_VERBOSE' => defined('DEBUG_VERBOSE') ? DEBUG_VERBOSE : 2,
	'DEBUG_WEB_CONSOLE' => defined('DEBUG_WEB_CONSOLE') ? DEBUG_WEB_CONSOLE : true,
	'DEBUG_LOG_CONSOLE' => defined('DEBUG_LOG_CONSOLE') ? DEBUG_LOG_CONSOLE : false,
];

// Save settings
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_settings'])) {

	$content = "<?php\n";
	$content .= "/**\n";
	$content .= " * @filesource /include/custom_settings.php\n";
	$content .= " * UI settings (overridable). Do not edit this file manually\n";
	$content .= " * Use /admin/ui_settings.php to modify these settings via web-interface\n";
	$content .= " * @generated " . date('Y-m-d H:i:s') . "\n";
	$content .= " */\n\n";

	$content .= "// Interface elements\n";
	$content .= "define('SHOW_AUDIO_MONITOR', " . (isset($_POST['SHOW_AUDIO_MONITOR']) ? 'true' : 'false') . ");\n";
	$content .= "define('SHOW_MACROS', " . (isset($_POST['SHOW_MACROS']) ? 'true' : 'false') . ");\n";
	$content .= "define('SHOW_CON_DETAILS', " . (isset($_POST['SHOW_CON_DETAILS']) ? 'true' : 'false') . ");\n";
	$content .= "define('SHOW_RADIO_ACTIVITY', " . (isset($_POST['SHOW_RADIO_ACTIVITY']) ? 'true' : 'false') . ");\n";
	$content .= "define('SHOW_NET_ACTIVITY', " . (isset($_POST['SHOW_NET_ACTIVITY']) ? 'true' : 'false') . ");\n";
	$content .= "define('SHOW_RF_ACTIVITY', " . (isset($_POST['SHOW_RF_ACTIVITY']) ? 'true' : 'false') . ");\n\n";

	$content .= "// History tables limits\n";
	$content .= "define('NET_ACTIVITY_LIMIT', " . (int)$_POST['NET_ACTIVITY_LIMIT'] . ");\n";
	$content .= "define('RF_ACTIVITY_LIMIT', " . (int)$_POST['RF_ACTIVITY_LIMIT'] . ");\n\n";

	$content .= "// WebSocket real-time updates\n";
	$content .= "define('WS_ENABLED', " . (isset($_POST['WS_ENABLED']) ? 'true' : 'false') . ");\n";

	$content .= "// AJAX update interval (ms)\n";
	$content .= "define('UPDATE_INTERVAL', " . (int)$_POST['UPDATE_INTERVAL'] . ");\n\n";

	$content .= "// Multilanguage support\n";
	$content .= "define('LANGUAGE_SUPPORT', " . (isset($_POST['LANGUAGE_SUPPORT']) ? 'true' : 'false') . ");\n\n";

	$content .= "// Debug mode\n";
	$content .= "define('DEBUG', " . (isset($_POST['DEBUG']) ? 'true' : 'false') . ");\n";
	$content .= "define('DEBUG_VERBOSE', " . (int)$_POST['DEBUG_VERBOSE'] . ");\n";
	$content .= "define('DEBUG_WEB_CONSOLE', " . (isset($_POST['DEBUG_WEB_CONSOLE']) ? 'true' : 'false') . ");\n";
	$content .= "define('DEBUG_LOG_CONSOLE', " . (isset($_POST['DEBUG_LOG_CONSOLE']) ? 'true' : 'false') . ");\n";

	// Create backup
	if (file_exists($customSettingsFile)) {
		copy($customSettingsFile, $customSettingsFile . '.backup.' . date('YmdHis'));
	}

	if (file_put_contents($customSettingsFile, $content)) {
		$message = getTranslation('Settings saved successfully') . ' ' . getTranslation('Refresh dashboard to apply changes');
		$messageType = 'success';
		// Update current settings
		$settings = [
			'SHOW_AUDIO_MONITOR' => isset($_POST['SHOW_AUDIO_MONITOR']),
			'SHOW_MACROS' => isset($_POST['SHOW_MACROS']),
			'SHOW_CON_DETAILS' => isset($_POST['SHOW_CON_DETAILS']),
			'SHOW_RADIO_ACTIVITY' => isset($_POST['SHOW_RADIO_ACTIVITY']),
			'SHOW_NET_ACTIVITY' => isset($_POST['SHOW_NET_ACTIVITY']),
			'NET_ACTIVITY_LIMIT' => (int)$_POST['NET_ACTIVITY_LIMIT'],
			'SHOW_RF_ACTIVITY' => isset($_POST['SHOW_RF_ACTIVITY']),
			'RF_ACTIVITY_LIMIT' => (int)$_POST['RF_ACTIVITY_LIMIT'],
			'WS_ENABLED' => isset($_POST['WS_ENABLED']),
			'UPDATE_INTERVAL' => (int)$_POST['UPDATE_INTERVAL'],
			'LANGUAGE_SUPPORT' => isset($_POST['LANGUAGE_SUPPORT']),
			'DEBUG' => isset($_POST['DEBUG']),
			'DEBUG_VERBOSE' => (int)$_POST['DEBUG_VERBOSE'],
			'DEBUG_WEB_CONSOLE' => isset($_POST['DEBUG_WEB_CONSOLE']),
			'DEBUG_LOG_CONSOLE' => isset($_POST['DEBUG_LOG_CONSOLE']),
		];
	} else {
		$message = getTranslation('Error saving settings');
		$messageType = 'error';
	}
}

// Reset to defaults
if (isset($_POST['reset_settings'])) {
	if (file_exists($customSettingsFile)) {
		unlink($customSettingsFile);
		$message = getTranslation('Settings reset to defaults');
		$messageType = 'success';
		// Reload settings from main settings.php
		$settings = [
			'SHOW_AUDIO_MONITOR' => defined('SHOW_AUDIO_MONITOR') ? SHOW_AUDIO_MONITOR : true,
			'SHOW_MACROS' => defined('SHOW_MACROS') ? SHOW_MACROS : true,
			'SHOW_CON_DETAILS' => defined('SHOW_CON_DETAILS') ? SHOW_CON_DETAILS : true,
			'SHOW_RADIO_ACTIVITY' => defined('SHOW_RADIO_ACTIVITY') ? SHOW_RADIO_ACTIVITY : true,
			'SHOW_NET_ACTIVITY' => defined('SHOW_NET_ACTIVITY') ? SHOW_NET_ACTIVITY : true,
			'NET_ACTIVITY_LIMIT' => defined('NET_ACTIVITY_LIMIT') ? NET_ACTIVITY_LIMIT : 10,
			'SHOW_RF_ACTIVITY' => defined('SHOW_RF_ACTIVITY') ? SHOW_RF_ACTIVITY : true,
			'RF_ACTIVITY_LIMIT' => defined('RF_ACTIVITY_LIMIT') ? RF_ACTIVITY_LIMIT : 5,
			'WS_ENABLED' => defined('WS_ENABLED') ? WS_ENABLED : true,
			'UPDATE_INTERVAL' => defined('UPDATE_INTERVAL') ? UPDATE_INTERVAL : 3000,
			'LANGUAGE_SUPPORT' => defined('LANGUAGE_SUPPORT') ? LANGUAGE_SUPPORT : false,
			'DEBUG' => defined('DEBUG') ? DEBUG : false,
			'DEBUG_VERBOSE' => defined('DEBUG_VERBOSE') ? DEBUG_VERBOSE : 4,
			'DEBUG_WEB_CONSOLE' => defined('DEBUG_WEB_CONSOLE') ? DEBUG_WEB_CONSOLE : true,
			'DEBUG_LOG_CONSOLE' => defined('DEBUG_LOG_CONSOLE') ? DEBUG_LOG_CONSOLE : false,
		];
	}
}

function isChecked($value)
{
	return $value ? 'checked="checked"' : '';
}
?>
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= getTranslation('Dashboard UI Settings') ?></title>
	<script src="/scripts/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="/css/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/fonts/stylesheet.css">
	<link rel="stylesheet" href="/css/css.php">
	<link rel="stylesheet" href="/css/custom.css">
	<link rel="stylesheet" href="/css/websocket_control.css">
</head>

<body>
	<div class="container">
		<div class="header">
			<div class="SmallHeader shLeft noMob">
				<a style="border-bottom: 1px dotted;" class="tooltip" href="#">
					<?php echo getTranslation('Node Name'); ?>:
					<span>
						<strong><?php echo getTranslation('Node IP'); ?><br></strong>
						<?php echo str_replace(',', ',<br />', exec("hostname -I | awk '{print $1}'")); ?>
					</span>
					<?php echo exec('cat /etc/hostname'); ?>
				</a>
			</div>
			<h1><?= getTranslation('Dashboard UI Settings') ?></h1>

			<div class="navbar">
				<div class="headerClock">
					<span id="DateTime"><?= date('d-m-Y H:i:s') ?></span>
				</div>
				<a class="menudashboard" href="/index.php"><?php echo getTranslation('Back to Dashboard'); ?></a>
			</div>
		</div>

		<div class="contentwide">
			<?php if ($message): ?>
				<div class="message <?= $messageType ?>">
					<i class="fa <?= $messageType === 'success' ? 'fa-check-circle' : 'fa-exclamation-triangle' ?>"></i>
					<?= htmlspecialchars($message) ?>
				</div>
			<?php endif; ?>

			<form method="POST">
				<div class="action-buttons">
					<button type="submit" name="save_settings" class="btn btn-save">
						<i class="fa fa-save"></i> <?= getTranslation('Save Settings') ?>
					</button>
					<button type="submit" name="reset_settings" class="btn btn-reset" onclick="return confirm('<?= getTranslation('Reset all settings to defaults?') ?>');">
						<i class="fa fa-undo"></i> <?= getTranslation('Reset to Defaults') ?>
					</button>
				</div>
				<!-- Interface Elements -->
				<h2 class="ConfSec"><?= getTranslation('Interface Elements') ?></h2>
				<table>
					<colgroup>
						<col style="width: 25%;">
						<col style="width: 15%;">
						<col style="width: 60%;">
					</colgroup>
					<thead>
						<tr>
							<th><?= getTranslation('Constant') ?></th>
							<th><?= getTranslation('Value') ?></th>
							<th><?= getTranslation('Description') ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>SHOW_AUDIO_MONITOR</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_audio" class="toggle toggle-round-flat" type="checkbox"
												name="SHOW_AUDIO_MONITOR" <?= isChecked($settings['SHOW_AUDIO_MONITOR']) ?>>
											<label for="toggle_audio"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Show audio monitor button and controls') ?></td>
						</tr>
						<tr>
							<td>SHOW_MACROS</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_macros" class="toggle toggle-round-flat" type="checkbox"
												name="SHOW_MACROS" <?= isChecked($settings['SHOW_MACROS']) ?>>
											<label for="toggle_macros"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Show macros panel for quick commands') ?></td>
						</tr>
						<tr>
							<td>SHOW_CON_DETAILS</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_con" class="toggle toggle-round-flat" type="checkbox"
												name="SHOW_CON_DETAILS" <?= isChecked($settings['SHOW_CON_DETAILS']) ?>>
											<label for="toggle_con"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Show connection details block') ?></td>
						</tr>
						<tr>
							<td>SHOW_RADIO_ACTIVITY</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_radio" class="toggle toggle-round-flat" type="checkbox"
												name="SHOW_RADIO_ACTIVITY" <?= isChecked($settings['SHOW_RADIO_ACTIVITY']) ?>>
											<label for="toggle_radio"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Show radio activity (RX/TX status)') ?></td>
						</tr>
					</tbody>
				</table>

				<br>

				<!-- History Tables -->
				<h2 class="ConfSec"> <?= getTranslation('History Tables') ?></h2>
				<table>
					<colgroup>
						<col style="width: 25%;">
						<col style="width: 15%;">
						<col style="width: 60%;">
					</colgroup>
					<thead>
						<tr>
							<th><?= getTranslation('Constant') ?></th>
							<th><?= getTranslation('Value') ?></th>
							<th><?= getTranslation('Description') ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>SHOW_NET_ACTIVITY</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_net" class="toggle toggle-round-flat" type="checkbox"
												name="SHOW_NET_ACTIVITY" <?= isChecked($settings['SHOW_NET_ACTIVITY']) ?>>
											<label for="toggle_net"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Show network activity history') ?></td>
						</tr>
						<tr>
							<td>NET_ACTIVITY_LIMIT</td>
							<td class="center">
								<div class="filter-activity-max-wrap" style="padding-top:6px">
									<input class="filter-activity-max" style="width:60px;" type="number"
										name="NET_ACTIVITY_LIMIT" value="<?= $settings['NET_ACTIVITY_LIMIT'] ?>" min="1" max="50">
								</div>
							</td>
							<td class="left"><?= getTranslation('Number of records in NET activity table') ?></td>
						</tr>
						<tr>
							<td>SHOW_RF_ACTIVITY</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_rf" class="toggle toggle-round-flat" type="checkbox"
												name="SHOW_RF_ACTIVITY" <?= isChecked($settings['SHOW_RF_ACTIVITY']) ?>>
											<label for="toggle_rf"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Show RF activity history') ?></td>
						</tr>
						<tr>
							<td>RF_ACTIVITY_LIMIT</td>
							<td class="center">
								<div class="filter-activity-max-wrap" style="padding-top:6px">
									<input class="filter-activity-max" style="width:60px;" type="number"
										name="RF_ACTIVITY_LIMIT" value="<?= $settings['RF_ACTIVITY_LIMIT'] ?>" min="1" max="50">
								</div>
							</td>
							<td class="left"><?= getTranslation('Number of records in RF activity table') ?></td>
						</tr>
					</tbody>
				</table>

				<br>

				<!-- WebSocket & Performance -->
				<h2 class="ConfSec"><?= getTranslation('WebSocket & Performance') ?></h2>
				<table style="width: 100%; table-layout: fixed;">
					<colgroup>
						<col style="width: 25%;">
						<col style="width: 15%;">
						<col style="width: 60%;">
					</colgroup>
					<thead>
						<tr>
							<th><?= getTranslation('Constant') ?></th>
							<th><?= getTranslation('Value') ?></th>
							<th><?= getTranslation('Description') ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>WS_ENABLED</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_ws" class="toggle toggle-round-flat" type="checkbox"
												name="WS_ENABLED" <?= isChecked($settings['WS_ENABLED']) ?>>
											<label for="toggle_ws"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Enable WebSocket real-time updates. Applicable to the left status panel and radio activity status') ?></td>
						</tr>
						<tr>
							<td>UPDATE_INTERVAL</td>
							<td class="center">
								<div class="filter-activity-max-wrap" style="padding-top:6px">
									<input class="filter-activity-max" style="width:80px;" type="number"
										name="UPDATE_INTERVAL" value="<?= $settings['UPDATE_INTERVAL'] ?>" min="1000" max="10000" step="500">
									<span class="left" style="color: #888;">ms</span>
								</div>
							</td>
							<td class="left"><?= getTranslation('AJAX update interval (milliseconds). When WS_ENABLED is enabled, it affects the update frequency of history tables and connection details') ?></td>
						</tr>
					</tbody>
				</table>

				<br>

				<!-- Language & Debug -->
				<h2 class="ConfSec"> <?= getTranslation('Language & Debug') ?></h2>
				<table style="width: 100%; table-layout: fixed;">
					<colgroup>
						<col style="width: 25%;">
						<col style="width: 15%;">
						<col style="width: 60%;">
					</colgroup>
					<thead>
						<tr>
							<th><?= getTranslation('Constant') ?></th>
							<th><?= getTranslation('Value') ?></th>
							<th><?= getTranslation('Description') ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>LANGUAGE_SUPPORT</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_lang" class="toggle toggle-round-flat" type="checkbox"
												name="LANGUAGE_SUPPORT" <?= isChecked($settings['LANGUAGE_SUPPORT']) ?>>
											<label for="toggle_lang"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Enable multilingual support') ?></td>
						</tr>
						<tr>
							<td>DEBUG</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_debug" class="toggle toggle-round-flat" type="checkbox"
												name="DEBUG" <?= isChecked($settings['DEBUG']) ?>>
											<label for="toggle_debug"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Enable debug mode') ?></td>
						</tr>
						<tr>
							<td>DEBUG_VERBOSE</td>
							<td class="center">
								<div class="filter-activity-max-wrap" style="padding-top:6px">
									<input class="filter-activity-max" style="width:60px;" type="number"
										name="DEBUG_VERBOSE" value="<?= $settings['DEBUG_VERBOSE'] ?>" min="1" max="5">
								</div>
							</td>
							<td class="left"><?= getTranslation('Debug verbosity level (1-5)') ?></td>
						</tr>
						<tr>
							<td>DEBUG_WEB_CONSOLE</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_debug_web" class="toggle toggle-round-flat" type="checkbox"
												name="DEBUG_WEB_CONSOLE" <?= isChecked($settings['DEBUG_WEB_CONSOLE']) ?>>
											<label for="toggle_debug_web"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Output debug to browser console') ?></td>
						</tr>
						<tr>
							<td>DEBUG_LOG_CONSOLE</td>
							<td class="center">
								<div class="grid-container" style="display: inline-grid; grid-template-columns: auto 40px;">
									<div class="grid-item" style="padding: 10px 0 0 20px;"></div>
									<div class="grid-item">
										<div style="padding-top:6px;">
											<input id="toggle_debug_log" class="toggle toggle-round-flat" type="checkbox"
												name="DEBUG_LOG_CONSOLE" <?= isChecked($settings['DEBUG_LOG_CONSOLE']) ?>>
											<label for="toggle_debug_log"></label>
										</div>
									</div>
								</div>
							</td>
							<td class="left"><?= getTranslation('Output debug to server log') ?></td>
						</tr>
					</tbody>
				</table>

				<br>

				<!-- Action Buttons -->
				<div class="action-buttons">
					<button type="submit" name="save_settings" class="btn btn-save">
						<i class="fa fa-save"></i> <?= getTranslation('Save Settings') ?>
					</button>
					<button type="submit" name="reset_settings" class="btn btn-reset" onclick="return confirm('<?= getTranslation('Reset all settings to defaults?') ?>');">
						<i class="fa fa-undo"></i> <?= getTranslation('Reset to Defaults') ?>
					</button>
				</div>
			</form>

			<!-- Info -->
			<div class="settings-info">
				<?= getTranslation('Settings file') ?>: '/include/custom_settings.php'.
				<?= getTranslation('Last modified') ?>: <?= file_exists($customSettingsFile) ? date('Y-m-d H:i:s', filemtime($customSettingsFile))  : getTranslation('Not exists (using defaults)') ?>
			</div>
		</div>

		<div id="footer" class="footer">
			<?php include $_SERVER['DOCUMENT_ROOT'] . "/include/footer.php"; ?>
		</div>
	</div>

	<script>
		function updateClock() {
			const now = new Date();
			document.getElementById('DateTime').textContent =
				now.toLocaleDateString('ru-RU') + ' ' + now.toLocaleTimeString('ru-RU');
		}
		setInterval(updateClock, 1000);
	</script>
</body>

</html>